name:                feather
version:             0.1.0.0
github:              "libscott/feather"
license:             BSD3
author:              "Scott Sadler"
maintainer:          "scott@scottsadler.de"
copyright:           "2019 Scott Sadler"

extra-source-files:
- README.md

description:         A minimalistic and performant events dispatcher.

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- microlens-platform

library:
  source-dirs: src
  default-extensions: 
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeSynonymInstances
  - ViewPatterns

tests:
  feather-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - feather
